title: BaekhoLab Interactive Textbook
theme: minima
# For navigation, if your theme supports it:
nav:
  - title: Home
    url: /index.md
  - title: About
    url: /about.md
  - title: Blog
    url: /blog/
  - title: Exercises
    url: /exercises.md
  - title: Visualizations
    url: /visualizations.md
